build error: 'could not compile dependency gettext, mix compile failed. You can recompile this dependency with ==> gettext Compiled lib/gettext/extractor_agent.ex Compiled lib/gettext/interpolation.ex Compiled lib/gettext.ex Compiled lib/gettext/po/exceptions.ex Compiled lib/mix/tasks/compile.gettext.ex Compiled lib/gettext/po/tokenizer.ex Compiled lib/mix/tasks/gettext.extract.ex Compiled lib/mix/tasks/gettext.merge.ex Compiled lib/gettext/plural.ex
== Compilation error on file lib/gettext/po/translation.ex ==
** (UndefinedFunctionError) undefined function: MapSet.new/0 (module MapSet is not available)
    MapSet.new()
    lib/gettext/po/translation.ex:42: (module)
    (stdlib) erl_eval.erl:657: :erl_eval.do_apply/6

== Compilation error on file lib/gettext/po/plural_translation.ex ==
** (UndefinedFunctionError) undefined function: MapSet.new/0 (module MapSet is not available)
    MapSet.new()
    lib/gettext/po/plural_translation.ex:45: (module)
    (stdlib) erl_eval.erl:657: :erl_eval.do_apply/6

== Compilation error on file lib/gettext/po/parser.ex ==
** (CompileError) lib/gettext/po/parser.ex:85: Gettext.PO.Translation.__struct__/0 is undefined, cannot expand struct Gettext.PO.Translation
    (elixir) src/elixir_map.erl:55: :elixir_map.translate_struct/4
    (stdlib) lists.erl:1352: :lists.mapfoldl/3
    (stdlib) lists.erl:1352: :lists.mapfoldl/3
    (elixir) src/elixir_clauses.erl:26: :elixir_clauses.match/3
    (elixir) src/elixir_clauses.erl:35: :elixir_clauses.clause/7
    (elixir) src/elixir_def.erl:178: :elixir_def.translate_clause/7

== Compilation error on file lib/gettext/fuzzy.ex ==
** (CompileError) lib/gettext/fuzzy.ex:57: Gettext.PO.Translation.__struct__/0 is undefined, cannot expand struct Gettext.PO.Translation
    (elixir) src/elixir_map.erl:55: :elixir_map.translate_struct/4
    (stdlib) lists.erl:1352: :lists.mapfoldl/3
    (elixir) src/elixir_clauses.erl:26: :elixir_clauses.match/3
    (elixir) src/elixir_clauses.erl:35: :elixir_clauses.clause/7
    (elixir) src/elixir_def.erl:178: :elixir_def.translate_clause/7
    (elixir) src/elixir_def.erl:167: :elixir_def.translate_definition/8

== Compilation error on file lib/gettext/extractor.ex ==
** (CompileError) lib/gettext/extractor.ex:112: Gettext.PO.PluralTranslation.__struct__/0 is undefined, cannot expand struct Gettext.PO.PluralTranslation
    (elixir) src/elixir_map.erl:55: :elixir_map.translate_struct/4
    (elixir) src/elixir_clauses.erl:36: :elixir_clauses.clause/7
    (elixir) src/elixir_def.erl:178: :elixir_def.translate_clause/7
    (elixir) src/elixir_def.erl:167: :elixir_def.translate_definition/8
    (elixir) src/elixir_def.erl:82: :elixir_def.store_definition/9
    lib/gettext/extractor.ex:111: (module)

== Compilation error on file lib/gettext/merger.ex ==
** (CompileError) lib/gettext/merger.ex:123: Gettext.PO.Translation.__struct__/0 is undefined, cannot expand struct Gettext.PO.Translation
    (elixir) src/elixir_map.erl:55: :elixir_map.translate_struct/4
    (stdlib) lists.erl:1352: :lists.mapfoldl/3
    (elixir) src/elixir_clauses.erl:26: :elixir_clauses.match/3
    (elixir) src/elixir_clauses.erl:35: :elixir_clauses.clause/7
    (elixir) src/elixir_def.erl:178: :elixir_def.translate_clause/7
    (elixir) src/elixir_def.erl:167: :elixir_def.translate_definition/8

== Compilation error on file lib/gettext/po/translations.ex ==
** (CompileError) lib/gettext/po/translations.ex:80: Gettext.PO.Translation.__struct__/0 is undefined, cannot expand struct Gettext.PO.Translation
    (elixir) src/elixir_map.erl:55: :elixir_map.translate_struct/4
    (stdlib) lists.erl:1352: :lists.mapfoldl/3
    (elixir) src/elixir_clauses.erl:26: :elixir_clauses.match/3
    (elixir) src/elixir_clauses.erl:35: :elixir_clauses.clause/7
    (elixir) src/elixir_def.erl:178: :elixir_def.translate_clause/7
    (elixir) src/elixir_def.erl:167: :elixir_def.translate_definition/8
    (elixir) src/elixir_def.erl:82: :elixir_def.store_definition/9

== Compilation error on file lib/gettext/compiler.ex ==
** (CompileError) lib/gettext/compiler.ex:213: Gettext.PO.Translation.__struct__/0 is undefined, cannot expand struct Gettext.PO.Translation
    (elixir) src/elixir_map.erl:55: :elixir_map.translate_struct/4
    (stdlib) lists.erl:1352: :lists.mapfoldl/3
    (stdlib) lists.erl:1353: :lists.mapfoldl/3
    (elixir) src/elixir_clauses.erl:26: :elixir_clauses.match/3
    (elixir) src/elixir_clauses.erl:35: :elixir_clauses.clause/7
    (elixir) src/elixir_def.erl:178: :elixir_def.translate_clause/7

== Compilation error on file lib/gettext/po.ex ==
** (CompileError) lib/gettext/po.ex:230: Gettext.PO.Translation.__struct__/0 is undefined, cannot expand struct Gettext.PO.Translation
    (elixir) src/elixir_map.erl:55: :elixir_map.translate_struct/4
    (stdlib) lists.erl:1352: :lists.mapfoldl/3
    (elixir) src/elixir_clauses.erl:26: :elixir_clauses.match/3
    (elixir) src/elixir_clauses.erl:35: :elixir_clauses.clause/7
    (elixir) src/elixir_def.erl:178: :elixir_def.translate_clause/7
    (elixir) src/elixir_def.erl:167: :elixir_def.translate_definition/8 or update it with Running dependency resolution
Dependency resolution completed
  gettext: 0.10.0' -- i think i need to install erlang